
INIT: Using found mnist data
Traceback (most recent call last):
  File "RunTest.py", line 182, in <module>
    main(args)
  File "RunTest.py", line 88, in main
    df_train_losses, train_df, test_df, info = sf.init_data(info)
  File "/com.docker.devenvironments.code/project/large_models/supporting_functions.py", line 73, in init_data
    train_df = train_df.drop(columns='test').set_index('i')
  File "/usr/local/lib/python3.8/dist-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py", line 5488, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['i'] are in the columns"