
INIT: Using found mnist data
2022-04-05 15:39:16.684771: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: UNKNOWN ERROR (34)
2022-04-05 15:39:16.684843: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (69dc0e526fe3): /proc/driver/nvidia/version does not exist
2022-04-05 15:39:16.685083: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
INIT: Finished creating train dataset
   label  score
i
0      2    NaN
1      0    NaN
2      4    NaN
3      8    NaN
6      0    NaN
original [5514, 6314, 5599, 5707, 5431, 5058, 5516, 5840, 5484, 5531]
original 55994
original [1389, 1563, 1391, 1434, 1393, 1255, 1360, 1453, 1341, 1427]
original 14006
MAIN: Started Training
Batch =0
Batch =100
Batch =200
Batch =300
Batch =400
Batch =500
Batch =600
Batch =700
Batch =800
Batch =900
Batch =1000
Batch =1100
Batch =1200
Batch =1300
Batch =1400
Batch =1500
Batch =1600
Batch =1700
/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py:6982: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  return Index(sequences[0], name=names)
   label  score         0
i
0      2    NaN  0.012168
1      0    NaN  0.000648
2      4    NaN  0.019192
3      8    NaN  0.602287
6      0    NaN    0.0001
used 0 epoch
   label     score         0
i
0      2  0.012168  0.012168
1      0  0.000648  0.000648
2      4  0.019192  0.019192
3      8  0.602287  0.602287
6      0    0.0001    0.0001
       label  score         0
i
25367      2    0.0  0.000003
10752      2    1.0  0.000004
25534      2    2.0  0.000005
52691      0    3.0  0.000008
14744      2    4.0  0.000008
                                                     img  label  score
i
25367  [  0   0   0   0   0   0   0   0   0   0   0  ...      2    0.0
10752  [  0   0   0   0   0   0   0   0   0   0   0  ...      2    1.0
25534  [  0   0   0   0   0   0   0   0   0   0   0  ...      2    2.0
52691  [  0   0   0   0   0   0   0   0   0   0   0  ...      0    3.0
14744  [  0   0   0   0   0   0   0   0   0   0   0  ...      2    4.0
...                                                  ...    ...    ...
46638  [  0   0   0   0   0   0   0   0   0   0   0  ...      5    NaN
18922  [  0   0   0   0   0   0   0   0   0   0   0  ...      7    NaN
6022   [  0   0   0   0   0   0   0   0   0   0   0  ...      1    NaN
19746  [  0   0   0   0   0   0   0   0   0   0   0  ...      9    NaN
51775  [  0   0   0   0   0   0   0   0   0   0   0  ...      0    NaN
[55994 rows x 3 columns]
55994
[5514, 6314, 5599, 5707, 5431, 5058, 5516, 5840, 5484, 5531]
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
2022-04-05 15:41:46.519802: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
Epoch  1 , Loss:  0.5043448 , Accuracy:  0.8576508 , Test Loss:  0.28122184 , Test Accuracy:  0.91554636
Checkpoint saved
Batch =0
Batch =100
Batch =200
Traceback (most recent call last):
  File "RunTest.py", line 193, in <module>
    main(args)
  File "RunTest.py", line 134, in main
    col = sf.update_col(batch_loss,col,X[0],info) # = (i,current_epoch)
  File "/com.docker.devenvironments.code/project/large_models/supporting_functions.py", line 196, in update_col
    col = pd.concat([col,new_row],axis=0)
  File "/usr/local/lib/python3.8/dist-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/reshape/concat.py", line 346, in concat
    op = _Concatenator(
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/reshape/concat.py", line 539, in __init__
    self.new_axes = self._get_new_axes()
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/reshape/concat.py", line 609, in _get_new_axes
    return [
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/reshape/concat.py", line 610, in <listcomp>
    self._get_concat_axis if i == self.bm_axis else self._get_comb_axis(i)
  File "pandas/_libs/properties.pyx", line 37, in pandas._libs.properties.CachedProperty.__get__
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/reshape/concat.py", line 665, in _get_concat_axis
    concat_axis = _concat_indexes(indexes)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/reshape/concat.py", line 683, in _concat_indexes
    return indexes[0].append(indexes[1:])
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py", line 5120, in append
    return self._concat(to_concat, name)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py", line 5128, in _concat
    result = concat_compat(to_concat_vals)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/dtypes/concat.py", line 151, in concat_compat
    result = np.concatenate(to_concat, axis=axis)
  File "<__array_function__ internals>", line 5, in concatenate
KeyboardInterrupt