
INIT: Using found mnist data
2022-04-06 09:56:22.511361: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: UNKNOWN ERROR (34)
2022-04-06 09:56:22.511545: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (e175316c4453): /proc/driver/nvidia/version does not exist
2022-04-06 09:56:22.515295: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
INIT: Finished creating train dataset
   label  score
i
0      2    NaN
1      0    NaN
2      4    NaN
3      8    NaN
6      0    NaN
MAIN: Started Training
Length Calculated:  1750
Batch =0
Batch =100
Batch =200
Batch =300
Batch =400
Batch =500
Batch =600
Batch =700
Batch =800
Batch =900
Batch =1000
Batch =1100
Batch =1200
Batch =1300
Batch =1400
Batch =1500
Batch =1600
Batch =1700
used 0 epoch
label        0
score    55994
0            0
dtype: int64
df-len- 55994
nas- 50395
dataused-on-epoch-end- 5599
[1417, 135, 1076, 606, 455, 141, 867, 796, 98, 8]
Length Calculated:  438
/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py:6982: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  return Index(sequences[0], name=names)
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
2022-04-06 09:59:18.047451: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
Epoch  1 , Loss:  0.48964784 , Accuracy:  0.8686466 , Test Loss:  0.2584404 , Test Accuracy:  0.9221762
Checkpoint saved
Length Calculated:  175
Batch =0
Batch =100
/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py:6982: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  return Index(sequences[0], name=names)
use reduced grads
label        0
score    55994
0            0
1        50394
dtype: int64
df-len- 55994
nas- 43231
dataused-on-epoch-end- 12763
[1889, 799, 1673, 1348, 1213, 916, 1457, 1445, 955, 1068]
Length Calculated:  438
Epoch  2 , Loss:  0.0012605875 , Accuracy:  1.0 , Test Loss:  0.25947717 , Test Accuracy:  0.9235328
Length Calculated:  399
Batch =0
Batch =100
Batch =200
Batch =300
use reduced grads
label        0
score    55994
0            0
1            0
2        43226
dtype: int64
/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py:6982: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  return Index(sequences[0], name=names)
df-len- 55994
nas- 37637
dataused-on-epoch-end- 18357
[2410, 1521, 2194, 1885, 1757, 1443, 1994, 2007, 1569, 1577]
Length Calculated:  438
Epoch  3 , Loss:  0.100449376 , Accuracy:  0.9802632 , Test Loss:  0.26301628 , Test Accuracy:  0.9225332
Length Calculated:  574
Batch =0
Batch =100
Batch =200
Batch =300
Batch =400
Batch =500
Traceback (most recent call last):
  File "RunTest.py", line 191, in <module>
    main(args)
  File "RunTest.py", line 134, in main
    col = sf.update_col(batch_loss,col,X[0],info) # = (i,current_epoch)
  File "/com.docker.devenvironments.code/project/large_models/supporting_functions.py", line 197, in update_col
    col = pd.concat([col,new_row],axis=0)
  File "/usr/local/lib/python3.8/dist-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/reshape/concat.py", line 359, in concat
    return op.get_result()
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/reshape/concat.py", line 592, in get_result
    new_data = concatenate_managers(
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/internals/concat.py", line 224, in concatenate_managers
    elif _is_uniform_join_units(join_units):
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/internals/concat.py", line 556, in _is_uniform_join_units
    if first.dtype.kind == "V":
  File "pandas/_libs/properties.pyx", line 37, in pandas._libs.properties.CachedProperty.__get__
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/internals/blocks.py", line 354, in dtype
    @cache_readonly
KeyboardInterrupt