
INIT: Using found mnist data
2022-04-06 10:12:53.714863: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: UNKNOWN ERROR (34)
2022-04-06 10:12:53.714955: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (e175316c4453): /proc/driver/nvidia/version does not exist
2022-04-06 10:12:53.715338: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
INIT: Finished creating train dataset
   label  score
i
0      2    NaN
1      0    NaN
2      4    NaN
3      8    NaN
6      0    NaN
MAIN: Started Training
Length Calculated:  1750
Batch =0
Batch =100
Batch =200
Batch =300
Batch =400
Batch =500
Batch =600
Batch =700
Batch =800
Batch =900
Batch =1000
Batch =1100
Batch =1200
Batch =1300
Batch =1400
Batch =1500
Batch =1600
Batch =1700
used 0 epoch
label        0
score    55994
0            0
dtype: int64
pacing dataused  5599
df-len- 55994
nas- 50395
dataused-on-epoch-end- 5599
[1370, 89, 1039, 586, 448, 174, 765, 965, 155, 8]
Length Calculated:  438
/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py:6982: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  return Index(sequences[0], name=names)
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
2022-04-06 10:15:53.757018: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
Epoch  1 , Loss:  0.45178285 , Accuracy:  0.87609386 , Test Loss:  0.25557283 , Test Accuracy:  0.9228902
Checkpoint saved
Length Calculated:  175
Batch =0
Batch =100
/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py:6982: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  return Index(sequences[0], name=names)
use reduced grads
label        0
score    55994
0            0
1        50394
dtype: int64
pacing dataused  7465
df-len- 55994
nas- 43234
dataused-on-epoch-end- 12760
[1914, 765, 1671, 1327, 1188, 906, 1351, 1627, 992, 1019]
Length Calculated:  438
Traceback (most recent call last):
  File "RunTest.py", line 191, in <module>
    main(args)
  File "RunTest.py", line 129, in main
    for i, (X,Y) in enumerate(train_data_gen):
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/data_utils.py", line 486, in __iter__
    for item in (self[i] for i in range(len(self))):
  File "/usr/local/lib/python3.8/dist-packages/keras/utils/data_utils.py", line 486, in <genexpr>
    for item in (self[i] for i in range(len(self))):
  File "/com.docker.devenvironments.code/project/large_models/datagen.py", line 79, in __getitem__
    X, Y = self.__get_data(batches)
  File "/com.docker.devenvironments.code/project/large_models/datagen.py", line 72, in __get_data
    X_batch = np.asarray([self.__get_input(x, self.input_size) for x  in img_batch])
  File "/com.docker.devenvironments.code/project/large_models/datagen.py", line 72, in <listcomp>
    X_batch = np.asarray([self.__get_input(x, self.input_size) for x  in img_batch])
  File "/com.docker.devenvironments.code/project/large_models/datagen.py", line 56, in __get_input
    img = [y/255 for y in img]
  File "/com.docker.devenvironments.code/project/large_models/datagen.py", line 56, in <listcomp>
    img = [y/255 for y in img]
KeyboardInterrupt
Epoch  2 , Loss:  0.0019677463 , Accuracy:  0.9998214 , Test Loss:  0.2530428 , Test Accuracy:  0.92431813
Length Calculated:  399
Batch =0