INIT: Using found mnist data
INIT: Finished creating train dataset
   label  score
i
0      2    NaN
1      0    NaN
2      4    NaN
3      8    NaN
6      0    NaN
original [5514, 6314, 5599, 5707, 5431, 5058, 5516, 5840, 5484, 5531]
original 55994
original [1389, 1563, 1391, 1434, 1393, 1255, 1360, 1453, 1341, 1427]
original 14006
MAIN: Started Training
Batch =0
2022-04-05 16:50:21.383169: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: UNKNOWN ERROR (34)
2022-04-05 16:50:21.383289: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (69dc0e526fe3): /proc/driver/nvidia/version does not exist
2022-04-05 16:50:21.383665: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Batch =100
Batch =200
Batch =300
Batch =400
Batch =500
Batch =600
Batch =700
Batch =800
Batch =900
Batch =1000
Batch =1100
Batch =1200
Batch =1300
Batch =1400
Batch =1500
Batch =1600
Batch =1700
   label  score         0
i
0      2    NaN  0.004211
1      0    NaN  0.004538
2      4    NaN  0.040191
3      8    NaN  0.323333
6      0    NaN  0.001421
used 0 epoch
label        0
score    55994
0           26
dtype: int64
   label     score         0
i
0      2  0.004211  0.004211
1      0  0.004538  0.004538
2      4  0.040191  0.040191
3      8  0.323333  0.323333
6      0  0.001421  0.001421
       label  score         0
i
14616      3    0.0  0.000008
22807      3    1.0   0.00001
59711      0    2.0  0.000011
64383      3    3.0  0.000012
31509      3    4.0  0.000015
                                                     img  label  score
i
14616  [  0   0   0   0   0   0   0   0   0   0   0  ...      3    0.0
22807  [  0   0   0   0   0   0   0   0   0   0   0  ...      3    1.0
59711  [  0   0   0   0   0   0   0   0   0   0   0  ...      0    2.0
64383  [  0   0   0   0   0   0   0   0   0   0   0  ...      3    3.0
31509  [  0   0   0   0   0   0   0   0   0   0   0  ...      3    4.0
...                                                  ...    ...    ...
30616  [  0   0   0   0   0   0   0   0   0   0   0  ...      1    NaN
52317  [  0   0   0   0   0   0   0   0   0   0   0  ...      1    NaN
30682  [  0   0   0   0   0   0   0   0   0   0   0  ...      9    NaN
54709  [  0   0   0   0   0   0   0   0   0   0   0  ...      5    NaN
26310  [  0   0   0   0   0   0   0   0   0   0   0  ...      1    NaN
[55994 rows x 3 columns]
5599
[1430, 95, 1074, 710, 444, 182, 672, 830, 153, 9]
/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py:6982: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  return Index(sequences[0], name=names)
Epoch  1 , Loss:  0.47700745 , Accuracy:  0.8696398 , Test Loss:  0.26489905 , Test Accuracy:  0.9227689
Checkpoint saved
Batch =0
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
2022-04-05 16:52:51.226294: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
Batch =100
       label  score         0         1
i
14616      3    0.0  0.000008  0.000004
22807      3    1.0   0.00001  0.000013
59711      0    2.0  0.000011  0.000008
64383      3    3.0  0.000012  0.000005
31509      3    4.0  0.000015  0.000014
use reduced grads
label        0
score    55994
0           26
1        50426
dtype: int64
/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py:6982: FutureWarning: In a future version, the Index constructor will not infer numeric dtypes when passed object-dtype sequences (matching Series behavior)
  return Index(sequences[0], name=names)
Traceback (most recent call last):
  File "RunTest.py", line 193, in <module>
    main(args)
  File "RunTest.py", line 142, in main
    df_train_losses = sf.scoring_func(df_train_losses,info) # =(i|score,0,1,2...)
  File "/com.docker.devenvironments.code/project/large_models/supporting_functions.py", line 149, in scoring_func
    df['score'] = calc_grad(n,df.iloc[:,-n:])
  File "/com.docker.devenvironments.code/project/large_models/supporting_functions.py", line 115, in calc_grad
    model = linear_model.LinearRegression().fit(x,y)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_base.py", line 662, in fit
    X, y = self._validate_data(
  File "/usr/local/lib/python3.8/dist-packages/sklearn/base.py", line 581, in _validate_data
    X, y = check_X_y(X, y, **check_params)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py", line 979, in check_X_y
    y = _check_y(y, multi_output=multi_output, y_numeric=y_numeric)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py", line 989, in _check_y
    y = check_array(
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py", line 800, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/usr/local/lib/python3.8/dist-packages/sklearn/utils/validation.py", line 114, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').