
INIT: Cannot find  mnist  data, downloading now...
2022-04-08 12:53:05.906617: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-08 12:53:06.786633: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 11433 MB memory:  -> device: 0, name: TITAN X (Pascal), pci bus id: 0000:04:00.0, compute capability: 6.1
[Errno 2] No such file or directory: '/user/HS223/ad00878/PhD/curriculum_over_time/project/large_models/datasets/mnist'
Traceback (most recent call last):
  File "RunTest.py", line 224, in <module>
    main(args)
  File "RunTest.py", line 92, in main
    df_train_losses, train_df, test_df, info = sf.init_data(info)
  File "/user/HS223/ad00878/PhD/curriculum_over_time/project/large_models/supporting_functions.py", line 61, in init_data
    df.to_csv(info.data_path + info.dataset_name + '/imagedata.csv')
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/generic.py", line 3551, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/formats/format.py", line 1180, in to_csv
    csv_formatter.save()
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/formats/csvs.py", line 241, in save
    with get_handle(
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 697, in get_handle
    check_parent_directory(str(handle))
  File "/usr/local/lib/python3.8/dist-packages/pandas/io/common.py", line 571, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/user/HS223/ad00878/PhD/curriculum_over_time/project/large_models/datasets/mnist'